[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyCdGECfXNZqUe2fTmo8dptYm1g4JxVG_Rc"
  VITE_BACKEND_URL = "https://mietmich.adaptable.app"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
